URL → HTTP_ADDRESS
URL → FTP_ADDRESS
URL → TELNET_ADDRESS
URL → MAILTO_ADDRESS
HTTP_ADDRESS → "http://" HOST_PORT
HTTP_ADDRESS → "http://" HOST_PORT "/" PATH
HTTP_ADDRESS → "http://" HOST_PORT "?" SEARCH
HTTP_ADDRESS → "http://" HOST_PORT "/" PATH "?" SEARCH
FTP_ADDRESS → "ftp://" LOGIN "/" PATH
TELNET_ADDRESS → "telnet://" LOGIN
MAILTO_ADDRESS → "mailto:" XALPHAS "@" HOSTNAME
LOGIN → HOST_PORT
LOGIN → USER "@" HOST_PORT
LOGIN → USER ":" PASSWORD "@" HOST_PORT
HOST_PORT → HOSTNAME
HOST_PORT → HOSTNAME ":" PORT
HOSTNAME → XALPHAS
HOSTNAME → HOSTNAME "." XALPHAS
PORT → DIGITS
PATH → SEGMENT
PATH → PATH "/" SEGMENT
SEARCH → XALPHAS
SEARCH → SEARCH "+" XALPHAS
USER → XALPHAS
PASSWORD → XALPHAS
SEGMENT → SEGMENT XALPHAS
SEGMENT → ε
XALPHAS → XALPHA
XALPHAS → XALPHAS XALPHA
DIGITS → DIGIT
DIGITS → DIGITS DIGIT
XALPHA → ALPHA
XALPHA → DIGIT
ALPHA → "A" | .. | "Z" | "a" | .. | "z"
DIGIT → "0" | .. | "9"

URL → HTTP_ADDRESS
URL → FTP_ADDRESS
URL → TELNET_ADDRESS
URL → MAILTO_ADDRESS
HTTP_ADDRESS → "http://" HOST_PORT
HTTP_ADDRESS → "http://" HOST_PORT PATH
HTTP_ADDRESS → "http://" HOST_PORT "?" SEARCH
HTTP_ADDRESS → "http://" HOST_PORT PATH "?" SEARCH
FTP_ADDRESS → "ftp://" LOGIN PATH
TELNET_ADDRESS → "telnet://" LOGIN
MAILTO_ADDRESS → "mailto:" XALPHAS "@" HOSTNAME
LOGIN → HOST_PORT
LOGIN → USER "@" HOST_PORT
LOGIN → USER ":" PASSWORD "@" HOST_PORT
HOST_PORT → HOSTNAME
HOST_PORT → HOSTNAME ":" PORT
HOSTNAME → XALPHAS
HOSTNAME → HOSTNAME "." XALPHAS
PORT → DIGITS
PATH → "/" XALPHAS
PATH → PATH "/" XALPHAS
SEARCH → XALPHAS
SEARCH → SEARCH "+" XALPHAS
USER → XALPHAS
PASSWORD → XALPHAS
XALPHAS → XALPHA
XALPHAS → XALPHAS XALPHA
DIGITS → DIGIT
DIGITS → DIGITS DIGIT
XALPHA → ALPHA
XALPHA → DIGIT
ALPHA → "A" | .. | "Z" | "a" | .. | "z"
DIGIT → "0" | .. | "9"

URL → HTTP_ADDRESS
URL → FTP_ADDRESS
URL → TELNET_ADDRESS
URL → MAILTO_ADDRESS
HTTP_ADDRESS → "http://" HOST_PORT
HTTP_ADDRESS → "http://" HOST_PORT PATH
HTTP_ADDRESS → "http://" HOST_PORT "?" SEARCH
HTTP_ADDRESS → "http://" HOST_PORT PATH "?" SEARCH
FTP_ADDRESS → "ftp://" LOGIN PATH
TELNET_ADDRESS → "telnet://" LOGIN
MAILTO_ADDRESS → "mailto:" XALPHAS "@" HOSTNAME
LOGIN → XALPHAS
LOGIN → XALPHAS ":" XALPHAS
LOGIN → XALPHAS "@" HOST_PORT
LOGIN → XALPHAS ":" XALPHAS "@" HOST_PORT
HOST_PORT → HOSTNAME
HOST_PORT → HOSTNAME ":" PORT
HOSTNAME → XALPHAS
HOSTNAME → HOSTNAME "." XALPHAS
PORT → DIGITS
PATH → "/" XALPHAS
PATH → PATH "/" XALPHAS
SEARCH → XALPHAS
SEARCH → SEARCH "+" XALPHAS
USER → XALPHAS
PASSWORD → XALPHAS
XALPHAS → XALPHA
XALPHAS → XALPHAS XALPHA
DIGITS → DIGIT
DIGITS → DIGITS DIGIT
XALPHA → ALPHA
XALPHA → DIGIT
ALPHA → "A" | .. | "Z" | "a" | .. | "z"
DIGIT → "0" | .. | "9"
