URL → HTTP_ADDRESS
URL → FTP_ADDRESS
URL → TELNET_ADDRESS
URL → MAILTO_ADDRESS
HTTP_ADDRESS → "http://" HOST_PORT
HTTP_ADDRESS → "http://" HOST_PORT "/" PATH
HTTP_ADDRESS → "http://" HOST_PORT "?" SEARCH
HTTP_ADDRESS → "http://" HOST_PORT "/" PATH "?" SEARCH
FTP_ADDRESS → "ftp://" LOGIN "/" PATH
TELNET_ADDRESS → "telnet://" LOGIN
MAILTO_ADDRESS → "mailto:" XALPHAS "@" HOSTNAME
LOGIN → HOST_PORT
LOGIN → USER "@" HOST_PORT
LOGIN → USER ":" PASSWORD "@" HOST_PORT
HOST_PORT → HOSTNAME
HOST_PORT → HOSTNAME ":" PORT
HOSTNAME → XALPHAS
HOSTNAME → XALPHAS "." HOSTNAME
PORT → DIGITS
PATH → SEGMENT
PATH → SEGMENT "/" PATH
SEARCH → XALPHAS
SEARCH → XALPHAS "+" SEARCH
USER → XALPHAS
PASSWORD → XALPHAS
SEGMENT → XALPHAS SEGMENT
SEGMENT → ε
XALPHAS → XALPHA
XALPHAS → XALPHA XALPHAS
DIGITS → DIGIT
DIGITS → DIGIT DIGITS
XALPHA → ALPHA
XALPHA → DIGIT
ALPHA → "A" | .. | "Z" | "a" | .. | "z"
DIGIT → "0" | .. | "9"
